# config-secrets.yaml - All ConfigMaps and Secrets for the app and MySQL

# App ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config-v1
  namespace: default
  # Contains DB connection details for the Spring app
data:
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql-service:3306/javatechie"
  SPRING_DATASOURCE_USERNAME: "root"
  APP_PORT: "9191"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SPRING_PROFILES_ACTIVE: "default"
  SPRING_JPA_SHOW_SQL: "true"
---
# App Secret
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets-v1
  namespace: default
  # Contains DB password for the Spring app
type: Opaque
data:
  DB_PASSWORD: cGFzczEyMw== # pass123
---
# MySQL ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config-v1
  namespace: default
data:
  MYSQL_DATABASE: "javatechie"
  MYSQL_PORT: "3306"
---
# MySQL Secret
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets-v1
  namespace: default
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cGFzczEyMw==  # pass123 